# Generated by Django 4.0.5 on 2022-10-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='href',
            field=models.CharField(blank=True, default='/companies/', max_length=50, null=True),
        ),
    ]
