# Generated by Django 4.0.5 on 2022-10-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocate', '0002_company_href'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advocate',
            old_name='long_bio',
            new_name='bio',
        ),
        migrations.RemoveField(
            model_name='advocate',
            name='short_bio',
        ),
        migrations.RemoveField(
            model_name='company',
            name='href',
        ),
        migrations.AddField(
            model_name='advocate',
            name='username',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
